CRITICAL - 2021-01-26 23:16:38 --> pg_query(): Query failed: ERROR:  relation &quot;ref_modul_akses&quot; does not exist
LINE 4:                                             ref_modul_akses 
                                                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', '/Volumes/data/d...', 196, Array)
#1 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(196): pg_query(Resource id #178, 'SELECT\n        ...')
#2 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Database/BaseConnection.php(741): CodeIgniter\Database\Postgre\Connection->execute('SELECT\n        ...')
#3 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Database/BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT\n        ...')
#4 /Volumes/data/dataxampp/file/htdocs/surveypasar/app/Libraries/Navigation.php(47): CodeIgniter\Database\BaseConnection->query('SELECT\n        ...')
#5 /Volumes/data/dataxampp/file/htdocs/surveypasar/app/Filters/LoginFilter.php(21): App\Libraries\Navigation->cek_akses('Admin/Home')
#6 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Filters/Filters.php(173): App\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#7 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('admin/home', 'before')
#8 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Volumes/data/dataxampp/file/htdocs/surveypasar/public/index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-01-26 23:19:21 --> pg_query(): Query failed: ERROR:  relation &quot;ref_modul_akses&quot; does not exist
LINE 4:                                             ref_modul_akses 
                                                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', '/Volumes/data/d...', 196, Array)
#1 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(196): pg_query(Resource id #178, 'SELECT\n        ...')
#2 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Database/BaseConnection.php(741): CodeIgniter\Database\Postgre\Connection->execute('SELECT\n        ...')
#3 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Database/BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT\n        ...')
#4 /Volumes/data/dataxampp/file/htdocs/surveypasar/app/Libraries/Navigation.php(47): CodeIgniter\Database\BaseConnection->query('SELECT\n        ...')
#5 /Volumes/data/dataxampp/file/htdocs/surveypasar/app/Filters/LoginFilter.php(21): App\Libraries\Navigation->cek_akses('Admin/Home')
#6 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Filters/Filters.php(173): App\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#7 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('admin/home', 'before')
#8 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Volumes/data/dataxampp/file/htdocs/surveypasar/public/index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-01-26 23:19:28 --> pg_query(): Query failed: ERROR:  relation &quot;ref_modul_akses&quot; does not exist
LINE 4:                                             ref_modul_akses 
                                                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', '/Volumes/data/d...', 196, Array)
#1 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(196): pg_query(Resource id #178, 'SELECT\n        ...')
#2 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Database/BaseConnection.php(741): CodeIgniter\Database\Postgre\Connection->execute('SELECT\n        ...')
#3 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Database/BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT\n        ...')
#4 /Volumes/data/dataxampp/file/htdocs/surveypasar/app/Libraries/Navigation.php(47): CodeIgniter\Database\BaseConnection->query('SELECT\n        ...')
#5 /Volumes/data/dataxampp/file/htdocs/surveypasar/app/Filters/LoginFilter.php(21): App\Libraries\Navigation->cek_akses('Admin/Home')
#6 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Filters/Filters.php(173): App\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#7 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('admin', 'before')
#8 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Volumes/data/dataxampp/file/htdocs/surveypasar/public/index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-01-26 23:19:31 --> pg_query(): Query failed: ERROR:  relation &quot;ref_modul_akses&quot; does not exist
LINE 4:                                             ref_modul_akses 
                                                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', '/Volumes/data/d...', 196, Array)
#1 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(196): pg_query(Resource id #178, 'SELECT\n        ...')
#2 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Database/BaseConnection.php(741): CodeIgniter\Database\Postgre\Connection->execute('SELECT\n        ...')
#3 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Database/BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT\n        ...')
#4 /Volumes/data/dataxampp/file/htdocs/surveypasar/app/Libraries/Navigation.php(47): CodeIgniter\Database\BaseConnection->query('SELECT\n        ...')
#5 /Volumes/data/dataxampp/file/htdocs/surveypasar/app/Filters/LoginFilter.php(21): App\Libraries\Navigation->cek_akses('Admin/Home')
#6 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Filters/Filters.php(173): App\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#7 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('admin/home', 'before')
#8 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Volumes/data/dataxampp/file/htdocs/surveypasar/public/index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-01-26 23:28:16 --> pg_query(): Query failed: ERROR:  relation &quot;ref_modul_akses&quot; does not exist
LINE 4:                                             ref_modul_akses 
                                                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', '/Volumes/data/d...', 196, Array)
#1 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(196): pg_query(Resource id #179, 'SELECT\n        ...')
#2 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Database/BaseConnection.php(741): CodeIgniter\Database\Postgre\Connection->execute('SELECT\n        ...')
#3 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Database/BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT\n        ...')
#4 /Volumes/data/dataxampp/file/htdocs/surveypasar/app/Libraries/Navigation.php(47): CodeIgniter\Database\BaseConnection->query('SELECT\n        ...')
#5 /Volumes/data/dataxampp/file/htdocs/surveypasar/app/Filters/LoginFilter.php(21): App\Libraries\Navigation->cek_akses('Admin/Home')
#6 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Filters/Filters.php(173): App\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#7 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('admin/home', 'before')
#8 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Volumes/data/dataxampp/file/htdocs/surveypasar/public/index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-01-26 23:28:26 --> pg_query(): Query failed: ERROR:  relation &quot;ref_modul_akses&quot; does not exist
LINE 4:                                             ref_modul_akses 
                                                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', '/Volumes/data/d...', 196, Array)
#1 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php(196): pg_query(Resource id #178, 'SELECT\n        ...')
#2 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Database/BaseConnection.php(741): CodeIgniter\Database\Postgre\Connection->execute('SELECT\n        ...')
#3 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Database/BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT\n        ...')
#4 /Volumes/data/dataxampp/file/htdocs/surveypasar/app/Libraries/Navigation.php(47): CodeIgniter\Database\BaseConnection->query('SELECT\n        ...')
#5 /Volumes/data/dataxampp/file/htdocs/surveypasar/app/Filters/LoginFilter.php(21): App\Libraries\Navigation->cek_akses('Admin/Home')
#6 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Filters/Filters.php(173): App\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#7 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('admin/home', 'before')
#8 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Volumes/data/dataxampp/file/htdocs/surveypasar/public/index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-01-26 23:55:48 --> syntax error, unexpected '$grid' (T_VARIABLE)
#0 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/Router/Router.php(195): CodeIgniter\Router\Router->autoRoute('admin/refSeller...')
#1 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/CodeIgniter.php(793): CodeIgniter\Router\Router->handle('admin/refSeller...')
#2 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/CodeIgniter.php(364): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 /Volumes/data/dataxampp/file/htdocs/surveypasar/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /Volumes/data/dataxampp/file/htdocs/surveypasar/public/index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
